CREATE Table lessons
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    start_date  VARCHAR(100) NOT NULL,
    end_date  VARCHAR(100) NOT NULL,
    subject_id BIGINT REFERENCES lessons (id),
    teacher_id BIGINT REFERENCES users (id)
);