
CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    level VARCHAR(50),
    type_id BIGINT,
    lesson_id BIGINT
);

CREATE TABLE task_answer (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     user_id BIGINT REFERENCES users(id),
     task_id BIGINT REFERENCES task(id),
     answer TEXT NOT NULL,
     is_correct BOOLEAN,
     updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
