CREATE TABLE certificate (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             subject_id BIGINT NOT NULL REFERENCES subjects(id),
                             user_id BIGINT NOT NULL REFERENCES users(id),
                             title VARCHAR(100) NOT NULL,
                             description VARCHAR(255),
                             is_access BOOLEAN NOT NULL DEFAULT FALSE,
                             issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             progress_percentage INT NOT NULL CHECK (progress_percentage BETWEEN 0 AND 100)
);