CREATE Table categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(100) NOT NULL,
    isActive    BOOLEAN      NOT NULL
)