CREATE Table subjects
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(100) NOT NULL,
    code        VARCHAR(100) NOT NULL,
    credits     INTEGER      NOT NULL,
    description VARCHAR(255)
);