CREATE Table schedules
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(100) NOT NULL,
    isActive    BOOLEAN      NOT NULL,
    lesson_id   BIGINT       NOT NULL
);